# Generated by Django 5.2.1 on 2025-05-25 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='derivacion',
            name='usada_en_cita',
        ),
        migrations.AddField(
            model_name='cita',
            name='derivacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas', to='core.derivacion'),
        ),
        migrations.AddField(
            model_name='derivacion',
            name='cita_agendada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='derivacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('usada', 'Usada'), ('vencida', 'Vencida')], default='pendiente', max_length=15),
        ),
    ]
