# Generated by Django 5.2.1 on 2025-05-30 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_foto_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosAntropometricos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('peso', models.DecimalField(decimal_places=2, help_text='Peso en kilogramos', max_digits=5)),
                ('talla', models.DecimalField(decimal_places=2, help_text='Altura en centímetros', max_digits=5)),
                ('imc', models.DecimalField(blank=True, decimal_places=2, help_text='Índice de Masa Corporal', max_digits=5, null=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_antropometricos', to='core.cita')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datos_registrados', to='core.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_antropometricos', to='core.paciente')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_antropometricos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Datos Antropométricos',
                'verbose_name_plural': 'Datos Antropométricos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
