# Generated by Django 5.2.1 on 2025-05-30 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_datosantropometricos'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='fecha_lectura',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='objeto_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID del objeto relacionado', null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='objeto_relacionado',
            field=models.CharField(blank=True, help_text="Tipo de objeto relacionado (ej: 'cita', 'derivacion')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='url_redireccion',
            field=models.CharField(blank=True, help_text='URL a la que redirigir al hacer clic en la notificación', max_length=255, null=True),
        ),
    ]
