# Generated by Django 5.2.1 on 2025-05-31 00:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificacion_fecha_lectura_notificacion_objeto_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tratamientoprogramado',
            options={'ordering': ['-created_at'], 'verbose_name': 'Tratamiento Programado', 'verbose_name_plural': 'Tratamientos Programados'},
        ),
        migrations.AddField(
            model_name='tratamientoprogramado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tratamientoprogramado',
            name='fecha_fin_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tratamientoprogramado',
            name='notas_seguimiento',
            field=models.TextField(blank=True, help_text='Notas generales sobre el progreso del tratamiento'),
        ),
        migrations.AddField(
            model_name='tratamientoprogramado',
            name='sesiones_completadas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tratamientoprogramado',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='SeguimientoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_sesion', models.PositiveIntegerField()),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='pendiente', max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('evolucion', models.TextField(blank=True, help_text='Evolución del paciente en esta sesión')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seguimiento_sesion', to='core.cita')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='core.tratamientoprogramado')),
            ],
            options={
                'verbose_name': 'Seguimiento de Sesión',
                'verbose_name_plural': 'Seguimientos de Sesiones',
                'ordering': ['tratamiento', 'numero_sesion'],
                'unique_together': {('tratamiento', 'numero_sesion')},
            },
        ),
    ]
