# Generated by Django 5.2.3 on 2025-07-06 13:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tratamientoprogramado_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código interno del medicamento', max_length=20, unique=True)),
                ('nombre_generico', models.CharField(help_text='Nombre del principio activo', max_length=200)),
                ('nombre_comercial', models.CharField(help_text='Marca comercial', max_length=200)),
                ('concentracion', models.CharField(help_text='Ej: 500mg, 250mg/5ml', max_length=100)),
                ('forma_farmaceutica', models.CharField(choices=[('tableta', 'Tableta'), ('capsula', 'Cápsula'), ('jarabe', 'Jarabe'), ('suspension', 'Suspensión'), ('crema', 'Crema'), ('pomada', 'Pomada'), ('solucion', 'Solución'), ('inyectable', 'Inyectable'), ('gotas', 'Gotas'), ('spray', 'Spray'), ('ovulo', 'Óvulo'), ('supositorio', 'Supositorio')], default='tableta', max_length=20)),
                ('laboratorio', models.CharField(max_length=100)),
                ('stock_actual', models.IntegerField(default=0, help_text='Cantidad actual en inventario')),
                ('stock_minimo', models.IntegerField(default=10, help_text='Stock mínimo para alertas')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio por unidad', max_digits=10)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha de vencimiento del lote actual')),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_receta', models.BooleanField(default=True, help_text='Si requiere prescripción médica')),
                ('controlado', models.BooleanField(default=False, help_text='Si es medicamento controlado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicamento',
                'verbose_name_plural': 'Medicamentos',
                'ordering': ['nombre_comercial'],
            },
        ),
        migrations.AddField(
            model_name='seguimientosesion',
            name='mejoria_observada',
            field=models.TextField(blank=True, help_text='Mejorías observadas desde la última sesión'),
        ),
        migrations.AddField(
            model_name='seguimientosesion',
            name='observaciones_farmacologicas',
            field=models.TextField(blank=True, help_text='Observaciones sobre medicamentos y dosis'),
        ),
        migrations.AddField(
            model_name='seguimientosesion',
            name='observaciones_proxima_sesion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='seguimientosesion',
            name='proxima_sesion_recomendada',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='seguimientosesion',
            name='requiere_ajuste_medicamentos',
            field=models.BooleanField(default=False, help_text='Indica si requiere ajuste farmacológico'),
        ),
        migrations.AddField(
            model_name='seguimientosesion',
            name='sintomas_actuales',
            field=models.TextField(blank=True, help_text='Síntomas presentes en esta sesión'),
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_receta', models.CharField(help_text='Código único de la receta', max_length=20, unique=True)),
                ('fecha_prescripcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_dispensacion', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('dispensada', 'Dispensada'), ('parcial', 'Parcialmente Dispensada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('observaciones_medico', models.TextField(blank=True, help_text='Observaciones del médico prescriptor')),
                ('observaciones_farmacia', models.TextField(blank=True, help_text='Observaciones del farmacéutico')),
                ('vigencia_dias', models.IntegerField(default=30, help_text='Días de vigencia de la receta')),
                ('urgente', models.BooleanField(default=False, help_text='Si es una receta urgente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='core.cita')),
                ('farmaceutico', models.ForeignKey(blank=True, help_text='Farmacéutico que dispensó la receta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas_dispensadas', to=settings.AUTH_USER_MODEL)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_prescritas', to='core.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='core.paciente')),
                ('sesion_seguimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='core.seguimientosesion')),
            ],
            options={
                'verbose_name': 'Receta Médica',
                'verbose_name_plural': 'Recetas Médicas',
                'ordering': ['-fecha_prescripcion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_prescrita', models.IntegerField(help_text='Cantidad total prescrita')),
                ('dosis', models.CharField(help_text='Ej: 1 tableta cada 8 horas', max_length=100)),
                ('frecuencia', models.CharField(help_text='Ej: Cada 8 horas, 3 veces al día', max_length=100)),
                ('duracion_dias', models.IntegerField(help_text='Duración del tratamiento en días')),
                ('via_administracion', models.CharField(default='oral', help_text='Vía de administración', max_length=50)),
                ('instrucciones', models.TextField(help_text='Instrucciones específicas de administración')),
                ('cantidad_dispensada', models.IntegerField(default=0, help_text='Cantidad entregada al paciente')),
                ('fecha_dispensacion', models.DateTimeField(blank=True, null=True)),
                ('lote_dispensado', models.CharField(blank=True, help_text='Lote del medicamento dispensado', max_length=50)),
                ('sustituido', models.BooleanField(default=False, help_text='Si fue sustituido por genérico')),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicamento')),
                ('medicamento_sustituido', models.ForeignKey(blank=True, help_text='Medicamento genérico usado como sustituto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sustituciones', to='core.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.recetamedica')),
            ],
            options={
                'verbose_name': 'Detalle de Receta',
                'verbose_name_plural': 'Detalles de Recetas',
            },
        ),
        migrations.AddField(
            model_name='seguimientosesion',
            name='receta_seguimiento',
            field=models.ForeignKey(blank=True, help_text='Receta generada en esta sesión', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.recetamedica'),
        ),
    ]
