# Generated by Django 5.2.3 on 2025-07-06 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_medicamento_seguimientosesion_mejoria_observada_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_positivo', 'Ajuste Positivo'), ('ajuste_negativo', 'Ajuste Negativo'), ('vencimiento', 'Por Vencimiento'), ('dañado', 'Por Daño'), ('devolucion', 'Devolución')], max_length=20)),
                ('cantidad', models.IntegerField(help_text='Cantidad del movimiento')),
                ('motivo', models.TextField(help_text='Motivo del movimiento')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('lote_referencia', models.CharField(blank=True, help_text='Lote involucrado', max_length=50)),
                ('proveedor', models.CharField(blank=True, help_text='Proveedor en caso de entrada', max_length=200)),
                ('precio_unitario_momento', models.DecimalField(blank=True, decimal_places=2, help_text='Precio unitario al momento del movimiento', max_digits=10, null=True)),
                ('stock_anterior', models.IntegerField(help_text='Stock antes del movimiento')),
                ('stock_nuevo', models.IntegerField(help_text='Stock después del movimiento')),
                ('numero_factura', models.CharField(blank=True, help_text='Número de factura o documento', max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='core.medicamento')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario que realizó el movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'ordering': ['-fecha_movimiento'],
            },
        ),
    ]
