# Estados de cita
ESTADO_CITA_PROGRAMADA = 'PROGRAMADA'
ESTADO_CITA_ATENDIDA = 'ATENDIDA'
ESTADO_CITA_CANCELADA = 'CANCELADA'
ESTADO_CITA_INASISTENCIA = 'INASISTENCIA'

# Otros estados y constantes que puedan ser necesarios
ORIGEN_CITA_ADMISION = 'ADMISION'
ORIGEN_CITA_DERIVACION = 'DERIVACION'
ORIGEN_CITA_SEGUIMIENTO = 'SEGUIMIENTO'
